sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 7.0
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=1
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration INTEGRATION_INDEX=1
cache:
  apt: true
  directories: $HOME/.composer/cache
matrix:
  exclude:
    - php: 7.0
      env: TEST_SUITE=static
before_install:
  - chmod +x ./dev/travis/skywire_before_install.sh
  - ./dev/travis/skywire_before_install.sh
install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --no-interaction --prefer-dist
before_script:
  - chmod +x ./dev/travis/skywire_before_script.sh
  - ./dev/travis/skywire_before_script.sh
script:
  - cd dev/tests/$TEST_SUITE
  - cp ./phpunit.xml.travis ./phpunit.xml
  - phpunit --testsuite Skywire
